apiVersion: v1
kind: Service
metadata:
  name: {{ include "whisper.whisper-llm-streamlit.fullname" . }}
  labels:
    {{- include "whisper.whisper-llm-streamlit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.whisper.service.type }}
  ports:
    - port: {{ .Values.whisper.service.port }}
      targetPort: {{ .Values.whisper.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "whisper.whisper-llm-streamlit.selectorLabels" . | nindent 4 }}
