{{- if .Values.whisper.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "whisper.whisper-llm-streamlit.serviceAccountName" . }}
  labels:
    {{- include "whisper.whisper-llm-streamlit.labels" . | nindent 4 }}
  {{- with .Values.whisper.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
